server:
  port: 1111

spring:
  security:
    user:
      name: user
      password: password

management:
  endpoints:
    web:
      base-path: /actuator
    enabled-by-default: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    # 状态页
    status-page-url-path: ${management.endpoints.web.base-path}/info
    # 健康检查
    health-check-url-path: ${management.endpoints.web.base-path}/health
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # 注册中心的职责是维护实例，不需要去检索服务
    fetch-registry: false

    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  # 是否要打开自我保护机制
  server:
    enable-self-preservation: false
